import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Search from "antd/es/transfer/search";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
        theme={{
          components: {
            Input: {
            },
          },
        }}
      >
      <html lang="en">
          <body>
            <AntdRegistry>{children}</AntdRegistry>
          </body>
      </html>
    </ConfigProvider>
  );
}
